any:
  - changed-files: "any/*"

all:
  - all:
    - changed-files: "**/*.txt"

head:
  - head-branch: "head-branch"

base:
  - base-branch: "main"

tests:
  - head-branch: ['^tests/', '^test/']
  - changed-files: ['tests/**/*', 'perf-tests/**/*']

dependencies:
  - head-branch: ['^deps/', '^dep/', '^dependabot/']
  - changed-files: ['go.mod', 'go.sum']
