name: PR Label Test

on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: joshdales/labeler@simpler-config
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true

